### ISSUE TITLE
Save Spawn Reset

### ISSUE THREAD

**Issue by Closior** [bnema/AnimalHusbandry_Eco#5]
No errors visible while mod is installed causes players to reset to spawn point after logout.

**Comment by No-Half-Measures** [comment]
Can confirm this is an issue, Keys also had this issue with his deployed patch for EM Machines yesterday and patched the issue out today, Something to-do with a bad unity scene?

**Comment by bnema** [comment]
Hello guys, i'll remove the latest version on mod.io just use the previous one for now until andy is proposing a fix for this.

**Comment by andykorth** [comment]
Oops! I was informed on discord that mods with enabled unity objects in them cause this issue. How strange. At least I know to look for it.

I will try to fix this today. Also I noticed the animal pend doesn't clear grass underneath it, so I'll look into that. Thanks for the report.

**Comment by padmanek** [comment]
> Hello guys, i'll remove the latest version on mod.io just use the previous one for now until andy is proposing a fix for this.

The version on mod.io right now doesnt contain any of my fixes that do not cause any issues btw. As you never updated the files on mod.io after my PRs.

**Comment by andykorth** [comment]
Thanks for a report, a pull request fixing this issue is here:
https://github.com/bnema/AnimalHusbandry_Eco/pull/6

I've tested it and my log in positions have been fine. More testing is appreciated.  Prior changes by @padmanek are still present in this pull request, and I did check them out and they look good. :)

**Comment by bnema** [comment]
Hello a pre-release containing the fix is available here : https://github.com/bnema/AnimalHusbandry_Eco/releases/tag/v1.3b

If I could have some feedbacks before merging and pushing to mod.io I would appreciate it !

Thank you

**Comment by Syrrion** [comment]
Hello ! I tried v1.3b but there's still an issue. When walking away from small pen, electric butchery or animal feeder, these items starts to fly off the ground as we are stepping away from them ; like if curve of planet wasn't taken in consideration when moving. To prevent that i had to use a previous unity3d file (but green on hover).

**Comment by andykorth** [comment]
Thanks! I bet I have the wrong shader selected on the meshes. The horizon bending happens as part of the vertex shader provided by the Eco devs. I'll double check that. Thanks!

It's a bit of a drag to recreate asset bundles without the source. Hopefully this is the last issue!
